# Generated by Django 4.2.6 on 2023-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userinfo_bio_alter_userinfo_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
