# Generated by Django 4.2.6 on 2023-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_picture.png', null=True, upload_to=''),
        ),
    ]
