# Generated by Django 4.2.6 on 2023-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userinfo_friends_post_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='psot_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
