# Generated by Django 4.2.6 on 2023-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='banner_default.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
